### ISSUE TITLE
Draw straight lines for relations

### ISSUE THREAD

**Issue by jcklie** [recogito/recogito-js#23]
Hello,
we are integrating recogito-js into an annotation editor. Right now, we we want to annotate word alignment. Vanilla recogit-js gets us almost there, but the problem is that the relation paths are overlapping. One solution could be to draw them straight instead of the otherweise nice looking jagged path. Can you give us a hint what we need to change in the code for this?  Would you be interested in us opening a PR for this?

![image](https://user-images.githubusercontent.com/934600/113920327-ec6f8000-97e4-11eb-8804-1fc3bea0f485.png)

Something like

![image](https://user-images.githubusercontent.com/934600/113920580-3ce6dd80-97e5-11eb-968b-f70fbcf4fb28.png)

That image is from a visualizer which has sadly no annotation capabilities. 
I suppose that is a bit of a use case that is not directly intended with recogito-js, but it would work for us very well.

**Comment by rsimon** [comment]
Hi,

hacking this should be (fairly) easy. The code that draws the connection is here:
https://github.com/recogito/recogito-js/blob/main/src/relations/Connection.js#L115-L197

(If I remember correctly, that handles the drawing for both cases: while the connection is still being drawn with the mouse; and also for connections already created.)

In your case, you can get rid of (almost) everything in that code section, and simply replace it with a straight SVG line.

**Comment by rsimon** [comment]
As far as a sustainable integration with the codebase is concerned: yes, I'd be interested in a pull request in principle! But then we'd probably need a mechanism to switch between modes from the outside, I guess. (E.g. an initialization option "connectionMode" or something.)

That, at least, would be a possible workaround. In an ideal world, RecogitoJS would be a bit more modular, so that connection functionality would be a separate plugin, decoupled from the main codebase. Then, replacing it with your own modified version would simply be a matter of attaching a custom connection plugin.

In the long run, remodeling RecogitoJS into a plugin-based system would be my goal (and I already made that transition in the  [image annotation sister project Annotorious](https://github.com/recogito/annotorious), which now works neatly with plugins). But I can't say when I'll get around to cleaning up RecogitoJS, since my current project work is focused on image annotation predominantly.

Anyways: hacking the `Connection` class would definitely get you the result you need. If you have more customization needs, however, then maybe it makes sense to think about setting up a plugin mechanism in RecogitoJS sooner rather than later. (And I'm definitely willing to help with that - let me know!)

**Comment by jcklie** [comment]
Hi,
thank you for your response. I will try to implement it as you proposed and push PRs for our customizations. For instance, we disabled  the annotation textbox popup as we have our own.

**Comment by rsimon** [comment]
Excellent, thanks:

> For instance, we disabled the annotation textbox popup as we have our own.

Great! It's actuallly planned to become available as a standard feature ("headless mode"). But it's only implemented in [Annotorious](https://github.com/recogito/annotorious) so far (see [here for an intro](https://recogito.github.io/guides/headless-mode/)). It will be great to (finally) have the same functionality in RecogitoJS, too.

**Comment by rsimon** [comment]
Just checking if there's any news on this. Otherwise, I'd close the issue.

**Comment by reckart** [comment]
Well, I did to a PR for the headless mode which is still pending your review: https://github.com/recogito/recogito-js/pull/38

**Comment by rsimon** [comment]
Yep, I still need to review the PR. I think there are still some repercussions on the lifecycle events that are not yet covered, so I might have to tweak that a little. My question was also about the straight lines feature, though.
